import { Experience, Project, SkillCategory, Certification } from "./types";

export const EXPERIENCES: Experience[] = [
  {
    id: "cub_lead",
    role: "experience.items.cub_lead.role",
    company: "experience.items.cub_lead.company",
    period: "experience.items.cub_lead.period",
    description: "experience.items.cub_lead.desc",
    images: [
      "/image/experience/10-1.jpg",
      "/image/experience/11-2.jpg",
      "/image/experience/11-3.jpg",
    ],
  },
  {
    id: "cub_robo",
    role: "experience.items.cub_robo.role",
    company: "experience.items.cub_robo.company",
    period: "experience.items.cub_robo.period",
    description: "experience.items.cub_robo.desc",
    images: [
      "/image/experience/10-1.jpg",
      "/image/experience/10-2.jpg",
      "/image/experience/10-3.jpg",
    ],
  },
  {
    id: "teco",
    role: "experience.items.teco.role",
    company: "experience.items.teco.company",
    period: "experience.items.teco.period",
    description: "experience.items.teco.desc",
    images: [
      "/image/experience/9-1.png",
      "/image/experience/9-2.png",
      "/image/experience/9-3.png",
    ],
  },
  {
    id: "military",
    role: "experience.items.military.role",
    company: "experience.items.military.company",
    period: "experience.items.military.period",
    description: "experience.items.military.desc",
    images: [
      "/image/experience/8-1.jpg",
      "/image/experience/8-2.jpg",
      "/image/experience/8-3.jpg",
    ],
  },
  {
    id: "master",
    role: "experience.items.master.role",
    company: "experience.items.master.company",
    period: "experience.items.master.period",
    description: "experience.items.master.desc",
    images: [
      "/image/experience/5-1.jpg",
      "/image/experience/7-2.jpg",
      "/image/experience/7-3.jpg",
    ],
  },
  {
    id: "mirdc",
    role: "experience.items.mirdc.role",
    company: "experience.items.mirdc.company",
    period: "experience.items.mirdc.period",
    description: "experience.items.mirdc.desc",
    images: [
      "/image/experience/6-1.jpg",
      "/image/experience/6-2.jpg",
      "/image/experience/6-3.jpg",
    ],
  },
  {
    id: "bachelor",
    role: "experience.items.bachelor.role",
    company: "experience.items.bachelor.company",
    period: "experience.items.bachelor.period",
    description: "experience.items.bachelor.desc",
    images: [
      "/image/experience/5-1.jpg",
      "/image/experience/5-2.jpg",
      "/image/experience/5-3.jpg",
    ],
  },
  {
    id: "digi",
    role: "experience.items.digi.role",
    company: "experience.items.digi.company",
    period: "experience.items.digi.period",
    description: "experience.items.digi.desc",
    images: [
      "/image/experience/4-1.jpg",
      "/image/experience/4-2.jpg",
      "/image/experience/4-3.jpg",
    ],
  },
  {
    id: "yaja",
    role: "experience.items.yaja.role",
    company: "experience.items.yaja.company",
    period: "experience.items.yaja.period",
    description: "experience.items.yaja.desc",
    images: [
      "/image/experience/3-1.jpg",
      "/image/experience/3-2.jpg",
      "/image/experience/3-3.jpg",
    ],
  },
  {
    id: "cio",
    role: "experience.items.cio.role",
    company: "experience.items.cio.company",
    period: "experience.items.cio.period",
    description: "experience.items.cio.desc",
    images: [
      "/image/experience/2-1.jpg",
      "/image/experience/2-2.jpg",
      "/image/experience/2-3.jpg",
    ],
  },
  {
    id: "highschool",
    role: "experience.items.highschool.role",
    company: "experience.items.highschool.company",
    period: "experience.items.highschool.period",
    description: "experience.items.highschool.desc",
    images: [
      "/image/experience/1-1.jpg",
      "/image/experience/1-2.jpg",
      "/image/experience/1-3.jpg",
    ],
  },
];

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: "frontend",
    titleKey: "skills.cat_frontend",
    skills: [
      { key: "frameworks", level: 95 },
      { key: "html", level: 95 },
      { key: "css", level: 90 },
      { key: "js_ts", level: 98 },
      { key: "rwd", level: 95 },
      { key: "storage", level: 90 },
      { key: "security", level: 92 },
      { key: "dom", level: 95 },
    ],
  },
  {
    id: "design",
    titleKey: "skills.cat_design",
    skills: [
      { key: "ui_ux", level: 70 },
      { key: "code_style", level: 90 },
      { key: "git", level: 90 },
      { key: "data_viz", level: 82 },
      { key: "three_d", level: 68 },
      { key: "wordpress", level: 77 },
      { key: "other_tech", level: 86 },
      { key: "tools", level: 88 },
    ],
  },
  {
    id: "backend",
    titleKey: "skills.cat_backend",
    skills: [
      { key: "node", level: 85 },
      { key: "auto_test", level: 80 },
      { key: "python", level: 72 },
      { key: "php", level: 70 },
      { key: "sql", level: 85 },
      { key: "data_mining", level: 75 },
      { key: "other_backend", level: 70 },
    ],
  },
  {
    id: "ai",
    titleKey: "skills.cat_ai",
    skills: [
      { key: "ai_stack", level: 74 },
      { key: "ai_prompt", level: 76 },
      { key: "ai_integration", level: 78 },
      { key: "ai_vector", level: 73 },
      { key: "cloud_ops", level: 86 },
    ],
  },
];

export const CERTIFICATIONS: Certification[] = [
  { id: "c1", name: "skills.certs.digi" },
  { id: "c2", name: "skills.certs.mobile" },
  { id: "c3", name: "skills.certs.soft_app_b" },
  { id: "c4", name: "skills.certs.ecom" },
  { id: "c5", name: "skills.certs.erp" },
  { id: "c6", name: "skills.certs.assist" },
  { id: "c7", name: "skills.certs.tqc_oop" },
  { id: "c8", name: "skills.certs.tqc_ecom" },
  { id: "c9", name: "skills.certs.tqc_pm" },
  { id: "c10", name: "skills.certs.tqc_proj" },
  { id: "c11", name: "skills.certs.biz_mgmt" },
  { id: "c12", name: "skills.certs.stats" },
  { id: "c13", name: "skills.certs.mos" },
  { id: "c14", name: "skills.certs.english" },
  { id: "c15", name: "skills.certs.lttc" },
  { id: "c16", name: "skills.certs.accounting" },
  { id: "c17", name: "skills.certs.soft_app_c" },
  { id: "c18", name: "skills.certs.soft_design" },
  { id: "c19", name: "skills.certs.web_design" },
  { id: "c20", name: "skills.certs.typing_cn" },
  { id: "c21", name: "skills.certs.typing_en" },
];

export const PROJECTS: Project[] = [
  {
    id: "laofu_fleet",
    size: "lg",
    title: "老夫子計程車行管理系統",
    description: "專為計程車行打造的智慧管理系統。整合車牌管理、司機管理、罰單追蹤與財務報表，提升營運效率。",
    tags: ["獨立開發", "獨立設計", "GCP", "Vertex AI", "resend", "better-auth", "minio", "prisma", "postgresql", "nestjs", "藍新金流", "ReactEmail", "React", "shadcn"],
    imageUrl: "/image/works/laofu.png",
    link: "https://laofufleet.com/",
  },
  {
    id: "cathay_mybank",
    size: "md",
    title: "Cathay Mybank 國泰世華網路銀行",
    description: "",
    tags: ["React", "TypeScript", "Chakra UI", "Jotai"],
    imageUrl: "/image/works/cathay_mybank.png",
    link: "https://www.cathaybk.com.tw/MyBank",
  },
  {
    id: "cathay_robo",
    size: "sm",
    title: "ROBO 智能投資",
    description: "",
    tags: ["Angular", "TypeScript", "Tailwind"],
    imageUrl: "/image/works/cathay_robo.png",
    link: "https://www.cathayrobo.com/",
  },
  {
    id: "imag_1",
    size: "sm",
    title: "VCA 春季活動網站",
    description: "",
    tags: ["獨立開發", "LINE Liff", "React", "TypeScript"],
    imageUrl: "/image/works/imag_1.png",
    link: "",
  },
  {
    id: "itts_3",
    size: "md",
    title: "WMS 倉儲管理系統",
    description: "",
    tags: [
      "獨立開發",
      "獨立設計",
      "Angular",
      "TypeScript",
      "OpenLayers",
      "ionic",
      "D3.js",
    ],
    imageUrl: "/image/works/itts_3.png",
    link: "",
  },
  {
    id: "itts_6",
    size: "md",
    title: "經銷商詢報價系統",
    description: "",
    tags: ["Three.js", "WebRTC", "WebSocket", "Angular", "TypeScript"],
    imageUrl: "/image/works/itts_6.png",
    link: "",
  },
  {
    id: "itts_2",
    size: "sm",
    title: "EIP 企業入口",
    description: "",
    tags: ["Angular", "TypeScript"],
    imageUrl: "/image/works/itts_2.png",
    link: "",
  },
  {
    id: "itts_7",
    size: "sm",
    title: "Mailroom 郵件收發系統",
    description: "",
    tags: ["PDA", "Angular", "TypeScript"],
    imageUrl: "/image/works/itts_7.png",
    link: "",
  },
  {
    id: "itts_5",
    size: "md",
    title: "ODS 派裝模擬系統",
    description: "",
    tags: ["獨立開發", "獨立設計", "Angular", "TypeScript", "SCSS"],
    imageUrl: "/image/works/itts_5.png",
    link: "",
  },
  {
    id: "itts_1",
    size: "sm",
    title: "SRM 供應商關係管理系統",
    description: "",
    tags: ["獨立開發", "獨立設計", "Angular", "TypeScript"],
    imageUrl: "/image/works/itts_1.png",
    link: "",
  },
  {
    id: "itts_4",
    size: "sm",
    title: "裝櫃模擬系統",
    description: "",
    tags: ["獨立開發", "獨立設計", "Angular", "TypeScript", "Three.js"],
    imageUrl: "/image/works/itts_4.png",
    link: "",
  },
  {
    id: "chanry_1",
    size: "sm",
    title: "內用點餐系統",
    description: "",
    tags: ["獨立開發", "獨立設計", "React", "NextJS", "TypeScript"],
    imageUrl: "/image/works/chanry_1.png",
    link: "",
  },
  {
    id: "movie_studio",
    size: "sm",
    title: "影像工作室官網",
    description: "",
    tags: ["獨立開發", "獨立設計", "JavaScript"],
    imageUrl: "/image/works/movie_studio.jpg",
    link: "",
  },
  {
    id: "lb",
    size: "sm",
    title: "雜誌媒體網站",
    description: "",
    tags: ["獨立開發", "獨立設計", "WordPress", "PHP", "JavaScript"],
    imageUrl: "/image/works/lb.jpg",
    link: "",
  },
];
